version: "3.8"

services:
  gazebo:
    build:
      image: panda_gazebo_sim
      target: panda_gazebo
      dockerfile: ./Dockerfile
      context: ./

    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ["panda_gazebo_sim", "roslaunch", "panda_gazebo", "panda_rviz.launch"]