version: "3.8"

services:
  gazebo:
    image: panda_gazebo_sim
    build:
      context: .
      target: panda_gazebo

    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ["roslaunch", "panda_gazebo", "panda_rviz.launch"]