version: "3.8"

services:
  gazebo:
    image: panda_gazebo_sim
    build:
      context: .
      target: panda_gazebo
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - WORLD_FILE=legibility_no_video.world
      - USE_GUI=true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./imgs:/tmp/camera_save_tutorial
    command: ["roslaunch", "panda_gazebo", "panda_gazebo.launch"]

  rviz:
    image: panda_gazebo_sim
    environment:
      - ROS_MASTER_URI=http://gazebo:11311
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./assets/catkin_ws/src/panda_gazebo/config/:/pandas_config/
    depends_on: 
      - gazebo
    command: ["rosrun", "rviz", "rviz", "-d", "/pandas_config/panda.rviz"]

  rospy:
    image: rospy3
    build:
      context: .
      target: rospy3
    environment:
      - ROS_MASTER_URI=http://gazebo:11311
    volumes:
      - ./:/ros_scripts
    depends_on: 
      - gazebo