version: "3.8"

services:
  gazebo:
    image: panda_gazebo_sim
    build:
      context: .
      target: panda_gazebo
    environment:
      - DISPLAY=unix$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ["roslaunch", "panda_gazebo", "panda_rviz.launch"]

  rviz:
    image: panda_gazebo_sim
    environment:
      - ROS_MASTER_URI=http://gazebo:11311
      - DISPLAY=unix$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./assets/catkin_ws/src/panda_gazebo/config/:/pandas_config/
    depends_on: 
      - gazebo
    command: ["rosrun", "rviz", "rviz", "-d /pandas_config/panda.rviz"]

  test:
    image: osrf/ros:kinetic-desktop-full-xenial
    environment:
      - ROS_MASTER_URI=http://gazebo:11311
    depends_on: 
      - gazebo