# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
    - panda_finger_joint1
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
panda_arm:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  gains:
    panda_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
panda_hand:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_hand_joint
    - panda_finger_joint1
    - panda_finger_joint2
  gains:
    panda_hand_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_finger_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_finger_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1